export default {
  REDUX_GET_TODO: 'REDUX_GET_TODO_SAGA',
  REDUX_ADD_TODO: 'REDUX_ADD_TODO_SAGA',
  REDUX_TOGGLE_COMPLETE: 'REDUX_TOGGLE_COMPLETE_SAGA',
  REDUX_DELETE_TODO: 'REDUX_DELETE_TODO_SAGA',
  REDUX_INITIAL: 'REDUX_INITIAL_SAGA',
}