export default {
  REDUX_GET_TODO: 'REDUX_GET_TODO_THUNK',
  REDUX_ADD_TODO: 'REDUX_ADD_TODO_THUNK',
  REDUX_TOGGLE_COMPLETE: 'REDUX_TOGGLE_COMPLETE_THUNK',
  REDUX_DELETE_TODO: 'REDUX_DELETE_TODO_THUNK',
  REDUX_INITIAL: 'REDUX_INITIAL_THUNK',
}