
export default {
    GET_SAGA_TODO_REQUEST: 'GET_SAGA_TODO_REQUEST',
    POST_SAGA_TODO_REQUEST: 'POST_SAGA_TODO_REQUEST',
    DELETE_SAGA_TODO_REQUEST: 'DELETE_SAGA_TODO_REQUEST',
    PATCH_SAGA_TODO_COMPLETE_REQUEST: 'PATCH_SAGA_TODO_COMPLETE_REQUEST',
}

